# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#future: true
#relative_permalinks: true

# Setup
title:               Sam Davyson
tagline:             ''
description:         ''
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sam Davyson
  url:               http://davyson.com
  email:             

# Custom vars
version:             1.0.0
gems: [jekyll-paginate]

theme: jekyll-theme-cayman